import type { PgnModel } from "../../../../parts/pgnparser/src/pgn_model";
import type { PlayerRecord } from "../../app/shell/model/app_state";
import type { PositionSearchHit, TextSearchHit } from "../../../../parts/resource/src/client/search_coordinator";
import type { MoveFrequencyEntry } from "../../../../parts/resource/src/domain/move_frequency";
import type { PgnResourceRef } from "../../../../parts/resource/src/domain/resource_ref";
import type { BoardShape } from "../../board/board_shapes";
import type { ShapePrefs } from "../../runtime/shape_prefs";
import type { EditorStylePrefs } from "../../runtime/editor_style_prefs";
import type { DefaultLayoutPrefs } from "../../runtime/default_layout_prefs";
import type { ChessSoundType } from "../../board/move_sound";

/** All service operations available to the component tree. */
export type AppStartupServices = {
  gotoFirst: () => void;
  gotoPrev: () => void;
  gotoNext: () => void;
  gotoLast: () => void;
  gotoMoveById: (moveId: string) => void;
  handleEditorArrowHotkey: (event: KeyboardEvent) => boolean;
  loadPgnText: (pgnText: string) => void;
  applyDeveloperDockRawPgn: (pgnText: string) => boolean;
  insertComment: (moveId: string, position: "before" | "after") => { id: string; rawText: string } | null;
  focusCommentAroundMove: (moveId: string, position: "before" | "after") => void;
  saveCommentText: (commentId: string, text: string) => void;
  applyDefaultIndent: () => void;
  saveBoardShapes: (moveId: string, shapes: BoardShape[]) => void;
  updateGameInfoHeader: (sessionId: string, key: string, value: string) => void;
  toggleMoveNag: (moveId: string, nag: string) => void;
  applyPgnModelEdit: (newModel: PgnModel, targetMoveId: string | null) => void;
  undo: () => void;
  redo: () => void;
  recordHistorySnapshot: () => void;
  openGameFromRef: (sourceRef: unknown) => void;
  openResource: () => void;
  openResourceFile: () => void;
  openResourceDatabase: () => void;
  openResourceDirectory: () => void;
  createResource: (kind: "db" | "directory" | "file") => void;
  selectResourceTab: (tabId: string) => void;
  closeResourceTab: (tabId: string) => void;
  deleteActiveGameInResource: () => Promise<void>;
  openNewGameDialog: () => void;
  newGameInActiveResource: (pgnText: string) => Promise<void>;
  openPgnText: (pgnText: string, options?: { preferredTitle?: string; sourceRef?: { kind: string; locator: string; recordId?: string } | null }) => void;
  reorderGameInResource: (sourceRef: unknown, afterSourceRef: unknown) => Promise<void>;
  searchByPosition: (positionHash: string, resourceRefs: PgnResourceRef[]) => Promise<PositionSearchHit[]>;
  searchByText: (query: string, resourceRefs: PgnResourceRef[]) => Promise<TextSearchHit[]>;
  explorePosition: (positionHash: string, resourceRefs: PgnResourceRef[]) => Promise<MoveFrequencyEntry[]>;
  openGameFromRecordId: (recordId: string) => Promise<void>;
  fetchGameMetadataByRecordId: (recordId: string) => Promise<Record<string, string> | null>;
  getActiveSessionResourceRef: () => { kind: string; locator: string } | null;
  getPlayerNameSuggestions: (query: string) => string[];
  getPlayers: () => PlayerRecord[];
  addPlayer: (record: PlayerRecord) => Promise<void>;
  deletePlayer: (record: PlayerRecord) => Promise<void>;
  updatePlayer: (oldRecord: PlayerRecord, updatedRecord: PlayerRecord) => Promise<void>;
  exportWebviewStorage: () => void;
  importWebviewStorage: () => void;
  switchSession: (sessionId: string) => void;
  closeSession: (sessionId: string) => void;
  flipBoard: () => void;
  openCurriculumPanel: () => void;
  setMenuOpen: (open: boolean) => void;
  openEditorStyleDialog: () => void;
  openDefaultLayoutDialog: () => void;
  setDevDockOpen: (open: boolean) => void;
  setActiveDevTab: (tab: "ast" | "pgn") => void;
  setLayoutMode: (mode: "plain" | "text" | "tree") => void;
  setShowEvalPills: (show: boolean) => void;
  setLocale: (locale: string) => void;
  setMoveDelayMs: (value: number) => void;
  playMoveSound: (soundType: ChessSoundType) => void;
  setSoundEnabled: (enabled: boolean) => void;
  setPositionPreviewOnHover: (enabled: boolean) => void;
  setDeveloperToolsEnabled: (enabled: boolean) => void;
  setShapePrefs: (prefs: ShapePrefs) => void;
  setEditorStylePrefs: (prefs: EditorStylePrefs) => void;
  setDefaultLayoutPrefs: (prefs: DefaultLayoutPrefs) => void;
  setSaveMode: (mode: string) => void;
  copyGameToClipboard: (fromMoveId?: string) => Promise<boolean>;
  saveActiveGameNow: () => void;
  saveSessionById: (sessionId: string) => void;
  discardActiveSessionChanges: () => Promise<void>;
  loadResourceSchemaId: (resourceRef: { kind: string; locator: string }) => Promise<string | null>;
  persistResourceSchemaId: (resourceRef: { kind: string; locator: string }, schemaId: string | null) => Promise<void>;
};
